name: CI Pipeline

# Trigger the workflow on push to any branch or when a pull request is made.
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment, you can also use windows-latest or macos-latest
    
    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Gradle requires Java to build)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Install Gradle (if not already installed)
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-wrapper-file: './gradlew'

      # Step 4: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew assemble

      # Step 5: Run tests using Gradle
      - name: Run tests with Gradle
        run: ./gradlew test
