name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (AdoptOpenJDK is now replaced with Adoptium Temurin)
      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Use v3 for latest setup-java
        with:
          java-version: '11'
          distribution: 'temurin'  # Use the Adoptium Temurin distribution

      # Step 3: Install Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-wrapper-file: './gradlew'

      # Step 4: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew assemble

      # Step 5: Run tests with Gradle
      - name: Run tests with Gradle
        run: ./gradlew test
